### ISSUE TITLE
Should we use Framer X?

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#11]
Can the Framer X app help us ship?

**Comment by zoenolan** [comment]
Framer X is currently MacOSX only.

To slightly hijack the issue. I do think using React to build the interface for zien makes sense. We have a route to using [React Native](https://facebook.github.io/react-native/) to build version for iOS, Android and Windows, alongside the web

**Comment by rehat101** [comment]
+1 for React or React Native to be specific

**Comment by zoenolan** [comment]
Marking this as closed, since it has been in done for a while now
