### ISSUE TITLE
Claim page state diagram

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#118]
'State machine' of the process

**Comment by zoenolan** [comment]
![Claim page state machine](https://user-images.githubusercontent.com/1663274/63210511-24452380-c0e7-11e9-83d9-a0ba767c0804.png)

**Comment by zoenolan** [comment]
The obvious follow on to this is [getting the flow working in Airtable](https://github.com/axna/zien/issues/121).

**Comment by zoenolan** [comment]
Updated without exposing the drop time
![Claim page state machine (1)](https://user-images.githubusercontent.com/1663274/63211555-a423bb80-c0f0-11e9-8a4e-0bd97121f01b.png)
