### ISSUE TITLE
Threat Modelling

### ISSUE THREAD

**Issue by zoenolan** [axna/zien#12]
As a user,  I would like to have a level of confidence that the system is secure and robust

**Acceptance Criteria**

- A [threat model](https://en.wikipedia.org/wiki/Threat_model) exists for the project

**Comment by rafaeljegundo** [comment]
@zoenolan I think this is important but hard for people to collaborate without extensive documentation, which I'm not sure if worth creating at MVP stage.

I'm thinking we perhaps could label this issues as "core-team" or assign them to ourselves. This would signal the separation between tasks which require high context and others which are more standard Open Source contributions that anyone can easily help

**Comment by zoenolan** [comment]
@rafaeljegundo I agree. Totally think this is something we need to cover as part of the core-team. Not part of the Alpha
