### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#120]

**Comment by pgholsgrove** [comment]
@rehat101 started a list here to iron out UI.

Universal

[ ] Discuss grid layout
[ ] Logo (Helvetica Neue, Medium 24px)
[ ] Menu (Helvetica Neue, Medium 14px)
[ ] Add Instagram / Twitter links to footer (Helvetica Neue, Medium 14px)

Fonts look off. Helvetica appears thicker? [Comparison](https://ica-bookstore.myshopify.com/collections/editions/products/michael-craig-martin-baseball-cap-2019).

Editions overview

[ ] Positioning of Scarce Editions title and style (Helvetica Neue, Regular 32px — h1)
[ ] Discuss grid layout
[ ] Title below images style (Helvetica Neue, Medium 16px — h2)
[ ] Date format: August 9th

Artwork page

[ ] Helvetica Neue titles (Medium 16px — h3)
[ ] Body text (Garamond, Regular 15px)
[ ] Artists name link (Garamond, Regular 15px #000)
[ ] Countdown timer (Corner offset 2px, less spacing around text)
[ ] Adjust vertical spacing between 'drop date' and drop registration button
[ ] Drop registration button style (80px height, add right chevron)
[ ] Horizontal spacing between images 2/3 to match vertical spacing to main image
[ ] Footer depth (180px from body, footer links 60px up from bottom)

Typeform styling

[ ] Discuss

**Comment by zoenolan** [comment]
How does this fit in with https://github.com/axna/zien/issues/84,  https://github.com/axna/zien/issues/85 and https://github.com/axna/zien/issues/116?

**Comment by rehat101** [comment]
I think we can consolidate all those issues with this one here.

**Comment by rehat101** [comment]
I'm not using px for font sizing. I'm using rem.

The base px is 14px so: 
1rem = 14px,
2rem = 28px

If you can update the above with rems that'd be great!

**Comment by pgholsgrove** [comment]
> I think we can consolidate all those issues with this one here.
Left #85 open to handle separately (however this should resolve most issues).

**Comment by pgholsgrove** [comment]
@rehat101 

Using base 16px

0.875rem = 14px,
0.9375rem = 15px,
1rem = 16px,
1.5rem = 24px,
2rem = 32px

**Comment by rehat101** [comment]
I've checked off the items. Can you please go through and verify them? @pgholsgrove

**Comment by pgholsgrove** [comment]
**New views**

- [ ] 'Dropping soon' state view
- [ ] 'Claim an edition' state view
- [ ] 'All gone' state view

**Comment by pgholsgrove** [comment]
@rehat101 

Capturing here remaining items:

- [ ] Grid layout
- [ ] Typeform customisation (upgraded to Premium)
- [ ] Mobile layout

Perhaps a call this week to run over?
