### ISSUE TITLE
Prototype of Claim page flow

### ISSUE THREAD

**Issue by zoenolan** [axna/zien#121]
Based off [the state machine](https://github.com/axna/zien/issues/118), build the flow in Airtable

**Comment by zoenolan** [comment]
Here is an end to end test of the Airtable code. No Typeform integration yet, as it made building a prototype simpler. Shared the link on slack,not here

**Comment by zoenolan** [comment]
One bit of a feedback, so far. Expose Unix timestamps

**Comment by zoenolan** [comment]
only added the registration start and end time as Unix timstamps, so as not to expose the drop time

**Comment by MichaelHirn** [comment]
## Data prerequisites for #103 

### Tables

#### AllUsers

Table with all users who can register for a drop in the alpha

*Required Fields*: `Name`, `Email`

#### AllRegistrations

Table with all users who have registered for a drop

*Required Fields*: `Name`, `Email`, `NotificationType` (3 hours, 1 hours, 10 min, ...), `ScarceEdition` (the drop they registered for), `Time when `DropOpen` Notification should go out for each NotificationType`

#### AllClaims

Table with all users who have tried to claim a drop

*Required Fields*: `Name`, `Email`, `ScarceEdition` (the drop they registered for), `The Edition they claimed/got assigned` (null or something if they weren't able to claim one; for not-successful email)

### Notifications

#### 1. `RegistrationOpen`

[Table:AllUsers](#AllUsers)

#### 2. `RegistrationConfirmation`

[Table:AllRegistrations](#AllRegistrations)

#### 3. `DropOpen`

[Table:AllRegistrations](#AllRegistrations)

#### 4. `DropOutcome`

[Table:AllClaims](#AllClaims)

**Comment by rehat101** [comment]
The following api shows all records:
`https://api.airtable.com/v0/appVDeCjTRiQR6xLq/Scarce%20Editions`

```json {
    "records": [
        {
            "id": "recCt6uX3wwzT6d2P",
            "fields": {
                "Name": "Ed Forieles #1",
                "Claimed Editions": [
                    "recDFiQFKJZSMo35D"
                ]
            },
            "createdTime": "2019-07-13T10:04:36.000Z"
        },
        {
            "id": "rect7z3obgfQjgqTg",
            "fields": {
                "Name": "Ed Forieles #2"
            },
            "createdTime": "2019-07-13T10:04:36.000Z"
        },
        {
            "id": "recuWEYNonDU907Ik",
            "fields": {
                "Name": "Ed Forieles #3"
            },
            "createdTime": "2019-07-13T10:04:36.000Z"
        }
    ]
}
```

I need the following fields for the feed page.

1. thumbnail url
2. edition name
3. edition artist name
4. edition year
5. drop date

**Comment by rehat101** [comment]
below api shows a record:
`https://api.airtable.com/v0/appVDeCjTRiQR6xLq/Scarce%20Editions/rect7z3obgfQjgqTg`

I need fields that would match this page:
https://app.zien.io/editions/ff-painful

let me know if you want me to elaborate on the above.

**Comment by zoenolan** [comment]
@rehat101 I thought we agreed to keep those as hardcoded data in the app for the MVP? Anyway I've added a AllScarceEditions table

**Comment by zoenolan** [comment]
@MichaelHirn For AllUsers, i ended up adding an EthereumAddress field. Same forAllClaims

**Comment by zoenolan** [comment]
Take a look at the new version of the Airtable and see if it works for both of you

**Comment by MichaelHirn** [comment]
Thanks @zoenolan, looks good.

I made a few changes:

- Changed type of `AllClaims:ScarceEdition` from `Text` to `LinkedRecord`
- Added fields `ScarceEditionName`, `ScarceEditionArtistsName`, `ScarceEditionYear`, `ScarceEditionNumberOfEditions` to `AllClaims`
- Added field `PhoneNumber` to `AllUsers`

Can you confirm that we are storing the phone number for users? Is it required or optional?

**Comment by zoenolan** [comment]
I thought the phone number was going to be required for now. We need them for notifications

**Comment by MichaelHirn** [comment]
Exactly, ok that's good

**Comment by pgholsgrove** [comment]
Outcomes from the first end-to-end test:

- [ ] Credentials are not yet submitted to Airtable after someone registers for the alpha
- [ ] Credentials are not yet submitted to Airtable after someone registers for a drop

**Comment by zoenolan** [comment]
Just thinking for the users,instead of having a user ID we could key them off the email address

**Comment by MichaelHirn** [comment]
I think that is a great idea. Let's do that

**Comment by zoenolan** [comment]
Made the changes
