### ISSUE TITLE
Typeform

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#133]
Updates to Typeform:

- [x] Collect phone number in Typeform during alpha registration (mandatory)
- [x] Remove phone number from drop registration flow
- [x] Create post drop registration screen in Typeform

**Comment by zoenolan** [comment]
Moved these from #121. These are writes to the Airtable not reads 

- [ ] Credentials are not yet submitted to Airtable after someone registers for the alpha
- [ ] Credentials are not yet submitted to Airtable after someone registers for a drop

**Comment by zoenolan** [comment]
Just tested the integration with Airtable for signups, moving on to the drop registration

**Comment by zoenolan** [comment]
Data added from drop registration

**Comment by zoenolan** [comment]
Ended adding a hidden field with the edition ID
