### ISSUE TITLE
People can invite friends to Zien

### ISSUE THREAD

**Issue by zoenolan** [axna/zien#16]

**Comment by rafaeljegundo** [comment]
@pgholsgrove is this still part of the MVP? I believe not but not sure.

On my experience while github issues work well to track tasks to be tackled, it's useful for them to reference some single source of truth which provides the overall roadmap we are tackling. In this case I believe that would be the alpha, with the mockups and any other documentation for its spec.

**Comment by zoenolan** [comment]
Not part of the Alpha
