### ISSUE TITLE
Dropping soon state change

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#162]
The 'Dropping soon' state change in the UI isn't triggering from Airtable correctly.

**Anticipated fix**
Update to the `RegistrationClosed` function in the `AllScarceEditions` table based on input in the `RegistrationClose` input.

**Comment by zoenolan** [comment]
So  I was playing around with this. The code is very simple basically Is the end date time before or after now. The documentation talks about a lag for the field updating but I don't want to mess with things in the middle of a drop

**Comment by zoenolan** [comment]
CLosing this, as we are moving off airtable
