### ISSUE TITLE
Notification updates

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#165]
- [x] Ensure all SMS messages arrive from 'ZIEN' (ZIENPilot and ZIENAlpha noticed on the 1 hour and 10 minute drop period notifications)
- [x] Ensure the 10 minute drop period isn't referenced as 15 minutes
- [x] Design 2 pre-drop notifications (48 hours / 12 hours)
- [x] Programme 2 pre-drop notifications (48 hours / 12 hours)

**Comment by zoenolan** [comment]
I guess we can close this now?
