### ISSUE TITLE
Create an account

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#21]
As an end user / artist, I want to create an account and profile (that I can edit from time to time).

**Comment by zoenolan** [comment]
I wonder since they will be the same flow, do we need separate stories for end users and artist. At least for now?

**Comment by pgholsgrove** [comment]
No, agreed. We don't need separate user flows. Edited this issue to reflect constraint.

**Comment by zoenolan** [comment]
Netlify has an [Identity services addon](https://www.netlify.com/docs/identity/) which is worth looking at, so we don't need to roll our own

**Comment by rafaeljegundo** [comment]
@pgholsgrove @zoenolan are we still going to require users to create an account for alpha? My understanding is we won't, but would be good to clarify here

**Comment by zoenolan** [comment]
The current agreement is not for the MVP/Alpha. So closing this issue for now. we can pick this up post Alpha
