### ISSUE TITLE
Create Scarce Editions

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#22]
As an artist, I would like to upload scarce editions that subscribers to my channel can collect.

We will operate this manually during v0.1.

Requirements:

- Choose existing NFT tool to generate tokens
- Implement a solution for storing data (IPFS?)

@zoenolan would you add anything here?

**Comment by rafaeljegundo** [comment]
@zoenolan @rehat101 how do you guys imagine the implementation strategy for this?

**Comment by zoenolan** [comment]
@rafaeljegundo Something like this

![Create a Scarce Edition](https://user-images.githubusercontent.com/1663274/61251607-de491880-a752-11e9-9af9-fee421f2e567.png)

So we can build the Airtable side without the blockchain first and have an end to end flow. Then add the blockchain code as either a script or automatic process

**Comment by zoenolan** [comment]
To add a little more detail. Each scarce edition has a separate table listing each of the edition and the address that owns that edition.

We have another table that lists which scarce editions are active

**Comment by zoenolan** [comment]
@pgholsgrove @rehat101 It would also be good to get your feedback on the design and #27

**Comment by zoenolan** [comment]
Thinking more about what we need to store, https://github.com/axna/zien/issues/91

**Comment by zoenolan** [comment]
> Choose existing NFT tool to generate tokens
I think this is mostly covered in https://github.com/axna/zien/issues/104

I'm not sure if we want to combine that issue with this one?

**Comment by zoenolan** [comment]
Basically we only need to [ERC721 Mintable](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC721/ERC721Mintable.sol)

**Comment by zoenolan** [comment]
and added a very basic implementation: https://github.com/axna/scarce-editions/pull/1
