### ISSUE TITLE
Claim a Scarce Edition

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#27]
As an end user or artist, I need to be able to claim a Scarce Edition. 

Requirement:

- Present a confirmation view on completion of payment process.
- Present success / failure screen.

**Comment by rafaeljegundo** [comment]
@pgholsgrove @zoenolan @rehat101 what are the actual steps involved in this process and how they connect to the different bits of our system?

**Comment by pgholsgrove** [comment]
@rafaeljegundo @zoenolan can we wrap Rafael's query into a task around the app architecture? (Discussed yesterday at CF#2). Separate task created to style the form: #82

**Comment by zoenolan** [comment]
@rafaeljegundo I was thinking something like this. so the blockchain operations are asynchronous compared to the app and Airtable data. Any thoughts?

![Claim a Scarce Edition](https://user-images.githubusercontent.com/1663274/61250367-69c0aa80-a74f-11e9-8f1b-3694b3bbcff1.png)

**Comment by zoenolan** [comment]
This is the only flow in the app that requires write access to the tables. to avoid exposing the Airtable API key we will need to use some sort of proxy.

**Comment by zoenolan** [comment]
Created a separate issue for the data model, https://github.com/axna/zien/issues/91

**Comment by zoenolan** [comment]
Can a single fan claim.multiple copies of a single edition?

**Comment by pgholsgrove** [comment]
No. A successful claim should be for one edition only.

**Comment by zoenolan** [comment]
I've got a (mostly) unstyled form working. I need to do a bit more testing but seems to be suitable for the MVP

**Comment by zoenolan** [comment]
The on chain part are still left but are covered by https://github.com/axna/zien/issues/104, so closing this
