### ISSUE TITLE
Share a Scarce Edition

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#28]
End users should be able to 'share' a Scarce Edition with others outside of Zien.

**Comment by rafaeljegundo** [comment]
@pgholsgrove can you elaborate on the intended behaviour? Do you mean sharing the opportunity to claim Scarce Editions in the broad sense, provide a link to show my friends what I claimed, or something else?

**Comment by zoenolan** [comment]
Not part of the Alpha
