### ISSUE TITLE
User flows

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#30]
Revised v0.1 user flow focusing on maximal learning from minimal product.

**Comment by zoenolan** [comment]
#27 covers claiming an edition

**Comment by zoenolan** [comment]
How does https://github.com/axna/zien/issues/19 overlap with this? Do we need both?

**Comment by pgholsgrove** [comment]
[User / tasks flows address the higher level 'user' and lower level 'tasks']

Closing this issue since we're addressing via #95
