### ISSUE TITLE
High level technical design

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#31]
High level design of the Zien MVP architecture.

**Comment by rehat101** [comment]
I have some ideas around this. To keep things agile, I think we should utilize AWS. 

**User management and Authentication** 
AWS Cognito

**DB**
API Gateway -> AWS Dynamo DB

**FrontEnd**
React Native

**Comment by rehat101** [comment]
I believe we have a few options on the front-end being React PWA or React Native.

React PWA would be a website and has capabilities to being nativ-ish. Also, uses the same low level primitives of a web application. React Native is of course hybrid but it's primitives are different compared to Web.

**Comment by MichaelHirn** [comment]
Agree, I'd also propose to leverage AWS. I don't have any personal experience with Cognito, Gateway, DynamoDB yet, but I am doing a lot of Terraform + AWS ECS, Lambda right now and it's really quick to set things up. Also, #8 would be easily possible with CodePipeline - has a great integration with the AWS stack.

And the infrastructure cost should be close to 0 if we are using these high-level services and are not renting entire instances.

### Frontend

Can we put React PWA in the App store? I'm just thinking if we want it in the App store for download (which probably has its own set of problems) or bypass it. What do you think @rehat101 @pgholsgrove @zoenolan?

**Comment by zoenolan** [comment]
I slightly lean towards React PWA. just so we don't need to deal with packaging and app stores for the alpha. The whole idea of the approval process just makes me nervous with deadlines. 

Agree around the points with AWS. Let that deal with most of the infrastructure. Allowing us to focus on the getting the Zien as polished as possible.

**Comment by zoenolan** [comment]
Marking this as closed, since it has been in done for a while now
