### ISSUE TITLE
Add route management system

### ISSUE THREAD

**Issue by rehat101** [axna/zien#37]
Add route management system on our PWA setup.

Proposed routes:

`/login`
`/signup`

`/app/feed`
`/app/artists/discover`
`/app/artists/subscribed`
`/app/collection`

Artist's profile:

`/app/profile/:id`
`/app/profile/:id/editions`
`/app/profile/:id/overview`
`/app/profile/:id/cv`
`/app/profile/:id/shows`

Anything after `/app` would be a protected route and will need access token from local storage to view data or even perform any actions.

Let me me know if protected route approach is aligned with you all. @zoenolan @MichaelHirn 
Am I missing any routes here? @pgholsgrove

**Comment by zoenolan** [comment]
Just thinking about the Artist profile. does making that we are talking about artists explict in the path make sense. Something like:

```
/app/artist/:id
/app/artist/:id/editions
/app/artist/:id/overview
/app/artist/:id/cv
/app/artist/:id/shows
```

**Comment by rehat101** [comment]
Makes sense! Nice one.
