### ISSUE TITLE
Provision AWS resources 

### ISSUE THREAD

**Issue by MichaelHirn** [axna/zien#38]
Peter provided AWS access #34 

Taher looked into DynamoDB and Cognito and requires those resources to be provisioned and configured directly.

This issue is to track any future AWS requirements. I will get started on providing the Terraform scripts to provision all required resources. @rehat101 feel free to comment if you need anything specific.

**Comment by rafaeljegundo** [comment]
@MichaelHirn what's the status on this?

**Comment by MichaelHirn** [comment]
I think the alpha version doesn't require much backend, so this is issue is postponed for now.

**Comment by zoenolan** [comment]
Ok, closing this for now then
