### ISSUE TITLE
Terms for v0.1

### ISSUE THREAD

**Issue by pgholsgrove** [axna/zien#44]
- Understand legal implications and find basic solution for accepting payments in v0.1
- Protect the interests of artists and works they create

**Comment by zoenolan** [comment]
[Take My Money! Accepting Payments on the Web](https://medium.com/table-xi/take-my-money-accepting-payments-on-the-web-d48719c1e3b4) ([Source Code](https://github.com/alexander-kh/take-my-money))

**Comment by zoenolan** [comment]
[VAT MOSS](https://www.gov.uk/government/collections/vat-moss-vat-on-sales-of-digital-services-in-the-eu)
