### ISSUE TITLE
Data Model

### ISSUE THREAD

**Issue by zoenolan** [axna/zien#91]
As a engineer, I need to understand how data is stored and processed inside the application

**Comment by zoenolan** [comment]
Just quickly coming up with a list of the data for each entity

**Artists**
- ArtistID
- Name
- Biography
- Website
- Instagram 
- Twitter

**Scarce Editions**
- EditionID
- Name
- Description
- Media
- Year
- ArtistID 
- List of images
- Drop Periods
- Costs
- Deadline
- Number of editions

**EditionID**
- Edition number
- Claimed address
- Transfer transaction

**Comment by zoenolan** [comment]
Artists and Scarce Editions are read only from the application. So could be represented as static data

**Comment by pgholsgrove** [comment]
@zoenolan suggestions:

**Scarce Editions**
- _Type_ instead of media
- Measurements
- Image rights

**EditionID**
- License

**Comment by zoenolan** [comment]
Added to the code by https://github.com/axna/zien/pull/96
